//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleTestAdapter {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoogleTestAdapter.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of actual test case durations: {0}.
        /// </summary>
        internal static string ActualTestCase {
            get {
                return ResourceManager.GetString("ActualTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added test case &apos;{0}&apos;.
        /// </summary>
        internal static string AddedTestCase {
            get {
                return ResourceManager.GetString("AddedTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Test case already in analyzer: {1}.
        /// </summary>
        internal static string AlreadyInAnalyzer {
            get {
                return ResourceManager.GetString("AlreadyInAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaching debugger to {0}.
        /// </summary>
        internal static string AttachDebuggerMessage {
            get {
                return ResourceManager.GetString("AttachDebuggerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average difference between expected and actual duration: {0} ms.
        /// </summary>
        internal static string AvgDifference {
            get {
                return ResourceManager.GetString("AvgDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}: Did not find file: {2}.
        /// </summary>
        internal static string BatchFileMissing {
            get {
                return ResourceManager.GetString("BatchFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}: Exited with code {2}, executed command: &apos;{3}&apos;.
        /// </summary>
        internal static string BatchReturnedExitCode {
            get {
                return ResourceManager.GetString("BatchReturnedExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Collected {1} test result(s) from result XML file {2}.
        /// </summary>
        internal static string CollectedResults {
            get {
                return ResourceManager.GetString("CollectedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Collected {1} test results from console output.
        /// </summary>
        internal static string CollectedResultsFromConsole {
            get {
                return ResourceManager.GetString("CollectedResultsFromConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command executed: &apos;{0} {1}&apos;, working directory: &apos;{2}&apos;.
        /// </summary>
        internal static string CommandExecuted {
            get {
                return ResourceManager.GetString("CommandExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exceeded maximum allowed command line length ({0}) after including {1} tests (next string length is {2}).
        /// </summary>
        internal static string CommandLineGeneratorError {
            get {
                return ResourceManager.GetString("CommandLineGeneratorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not list test cases for executable &apos;{0}&apos;: process execution failed with exit code {1}.
        /// </summary>
        internal static string CouldNotListTestCases {
            get {
                return ResourceManager.GetString("CouldNotListTestCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not terminate process {0} started at {1}: {2}.
        /// </summary>
        internal static string CouldNotTerminate {
            get {
                return ResourceManager.GetString("CouldNotTerminate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reason is probably a crash of test {0}.
        /// </summary>
        internal static string CrashTest {
            get {
                return ResourceManager.GetString("CrashTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Created {1} test results for tests which were neither found in result XML file nor in console output.
        /// </summary>
        internal static string CreatedTestResults {
            get {
                return ResourceManager.GetString("CreatedTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Could not delete test directory &apos;{1}&apos;: {2}.
        /// </summary>
        internal static string DeleteTestDir {
            get {
                return ResourceManager.GetString("DeleteTestDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not match custom regex {1}.
        /// </summary>
        internal static string DoesntMatchCustom {
            get {
                return ResourceManager.GetString("DoesntMatchCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not match default regex {1}.
        /// </summary>
        internal static string DoesntMatchDefault {
            get {
                return ResourceManager.GetString("DoesntMatchDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt; End of Output.
        /// </summary>
        internal static string EndOfOutputMessage {
            get {
                return ResourceManager.GetString("EndOfOutputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Exception while running tests: {1}.
        /// </summary>
        internal static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while resolving test locations and traits in {0}\n{1}.
        /// </summary>
        internal static string ExceptionResolving {
            get {
                return ResourceManager.GetString("ExceptionResolving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable {0} came from another computer and was blocked to help protect this computer..
        /// </summary>
        internal static string ExecutableError {
            get {
                return ResourceManager.GetString("ExecutableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}In particular: launch command prompt, change into directory &apos;{1}&apos;, and execute the following command to make sure your tests can be run in general.{2}{3} {4}.
        /// </summary>
        internal static string ExecuteSteps {
            get {
                return ResourceManager.GetString("ExecuteSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Execution has been cancelled: {1}.
        /// </summary>
        internal static string ExecutionCancelled {
            get {
                return ResourceManager.GetString("ExecutionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution is already running with settings for executable {0}, cannot switch to settings for {1}.
        /// </summary>
        internal static string ExecutionString {
            get {
                return ResourceManager.GetString("ExecutionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Execution took {1}.
        /// </summary>
        internal static string ExecutionTime {
            get {
                return ResourceManager.GetString("ExecutionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} expected durations have been found in actual durations.
        /// </summary>
        internal static string ExpectedDurations {
            get {
                return ResourceManager.GetString("ExpectedDurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of expected test case durations: {0}.
        /// </summary>
        internal static string ExpectedTestCase {
            get {
                return ResourceManager.GetString("ExpectedTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Test indicator file found for executable {0}.
        /// </summary>
        internal static string FileFound {
            get {
                return ResourceManager.GetString("FileFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Google Test indicator file found for executable {0}.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} test method symbols and {1} trait symbols in binary {2}.
        /// </summary>
        internal static string FoundTestMethod {
            get {
                return ResourceManager.GetString("FoundTestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file {0}. {1}.
        /// </summary>
        internal static string InvalidFile {
            get {
                return ResourceManager.GetString("InvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression &quot;{0}&quot;, exception message: {1}.
        /// </summary>
        internal static string InvalidRegularExpression {
            get {
                return ResourceManager.GetString("InvalidRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find source location for test {0}.
        /// </summary>
        internal static string LocationNotFoundError {
            get {
                return ResourceManager.GetString("LocationNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} matches custom regex {1}.
        /// </summary>
        internal static string MatchesCustom {
            get {
                return ResourceManager.GetString("MatchesCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} matches default regex {1}.
        /// </summary>
        internal static string MatchesDefault {
            get {
                return ResourceManager.GetString("MatchesDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must never be &lt; 0.
        /// </summary>
        internal static string NeverBeZero {
            get {
                return ResourceManager.GetString("NeverBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No known test case for test result of line &apos;{0}&apos; - are you repeating a test run, but tests have changed in the meantime?.
        /// </summary>
        internal static string NoKnownTestCaseMessage {
            get {
                return ResourceManager.GetString("NoKnownTestCaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command produced no output.
        /// </summary>
        internal static string NoOutput {
            get {
                return ResourceManager.GetString("NoOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No settings configured for test executable &apos;{0}&apos;; running with solution settings: {1}.
        /// </summary>
        internal static string NoSettingConfigured {
            get {
                return ResourceManager.GetString("NoSettingConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that no test output will be shown on the test console when executing tests concurrently!.
        /// </summary>
        internal static string NoTestOutputShown {
            get {
                return ResourceManager.GetString("NoTestOutputShown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to report..
        /// </summary>
        internal static string NothingToReport {
            get {
                return ResourceManager.GetString("NothingToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} tests in executable {1}.
        /// </summary>
        internal static string NumberOfTestsMessage {
            get {
                return ResourceManager.GetString("NumberOfTestsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running {0} tests....
        /// </summary>
        internal static string NumberOfTestsRunningMessage {
            get {
                return ResourceManager.GetString("NumberOfTestsRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file does not exist, did your tests crash?.
        /// </summary>
        internal static string OutputFileMissing {
            get {
                return ResourceManager.GetString("OutputFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output of command:.
        /// </summary>
        internal static string OutputOfCommand {
            get {
                return ResourceManager.GetString("OutputOfCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt; Output of command &apos;{1} {2}&apos;.
        /// </summary>
        internal static string OutputOfCommandMessage {
            get {
                return ResourceManager.GetString("OutputOfCommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel execution is selected in options, but tests are executed sequentially because debugger is attached..
        /// </summary>
        internal static string ParallelExecution {
            get {
                return ResourceManager.GetString("ParallelExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse duration in line &apos;{0}&apos;.
        /// </summary>
        internal static string ParseDurationMessage {
            get {
                return ResourceManager.GetString("ParseDurationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse pair &apos;{0}&apos;, exception message: {1}.
        /// </summary>
        internal static string ParsePair {
            get {
                return ResourceManager.GetString("ParsePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process has exited with code {0}.
        /// </summary>
        internal static string ProcessExitCode {
            get {
                return ResourceManager.GetString("ProcessExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read test durations: {0}.
        /// </summary>
        internal static string ReadTestDurationError {
            get {
                return ResourceManager.GetString("ReadTestDurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex &apos;{0}&apos; cannot be parsed: {1}.
        /// </summary>
        internal static string RegexParseError {
            get {
                return ResourceManager.GetString("RegexParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regex &apos;{0}&apos; timed out: {1}.
        /// </summary>
        internal static string RegexTimedOut {
            get {
                return ResourceManager.GetString("RegexTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Reported {1} test results to Visual Studio during test execution, executable: &apos;{2}&apos;.
        /// </summary>
        internal static string ReportedResultsToVS {
            get {
                return ResourceManager.GetString("ReportedResultsToVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Reported {1} test results to Visual Studio, executable: &apos;{2}&apos;, duration: {3}.
        /// </summary>
        internal static string ReportedTestResults {
            get {
                return ResourceManager.GetString("ReportedTestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restoring solution settings: {0}.
        /// </summary>
        internal static string RestoringSolutionSettings {
            get {
                return ResourceManager.GetString("RestoringSolutionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test {0}: Expected {1} ms, actual {2} ms.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}: Exception caught, message: &apos;{2}&apos;, executed command: &apos;{3}&apos;.
        /// </summary>
        internal static string RunBatchException {
            get {
                return ResourceManager.GetString("RunBatchException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Failed to run test executable &apos;{1}&apos;: {2}.
        /// </summary>
        internal static string RunExecutableError {
            get {
                return ResourceManager.GetString("RunExecutableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt;&gt; Scheduling statistics &lt;&lt;&lt;.
        /// </summary>
        internal static string SchedulingStats {
            get {
                return ResourceManager.GetString("SchedulingStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for test executable &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string SettingsMessage {
            get {
                return ResourceManager.GetString("SettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingsWrapper is already running with settings for an executable on thread &apos;{0}&apos;, cannot also be used by thread &apos;{1}&apos;.
        /// </summary>
        internal static string SettingsWrapperString {
            get {
                return ResourceManager.GetString("SettingsWrapperString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}Stack trace:{1}{2}.
        /// </summary>
        internal static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard deviation: {0} ms.
        /// </summary>
        internal static string StandardDeviation {
            get {
                return ResourceManager.GetString("StandardDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}: Successfully ran &apos;{2}&apos;.
        /// </summary>
        internal static string SuccessfullyRun {
            get {
                return ResourceManager.GetString("SuccessfullyRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated process {0} started at {1}.
        /// </summary>
        internal static string TerminatedProcess {
            get {
                return ResourceManager.GetString("TerminatedProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test case already in analyzer: {0}.
        /// </summary>
        internal static string TestCaseInAnalyzer {
            get {
                return ResourceManager.GetString("TestCaseInAnalyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1} test cases seem to not have been run - are you repeating a test run, but tests have changed in the meantime? Test cases:{2}{3}.
        /// </summary>
        internal static string TestCaseNotRun {
            get {
                return ResourceManager.GetString("TestCaseNotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test whether the following commands can be executed sucessfully on the command line (make sure all required binaries are on the PATH):{0}{1}.
        /// </summary>
        internal static string TestCommandCanBeRun {
            get {
                return ResourceManager.GetString("TestCommandCanBeRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test discovery was cancelled after {0} s for executable {1}.
        /// </summary>
        internal static string TestDiscoveryCancelled {
            get {
                return ResourceManager.GetString("TestDiscoveryCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test result file {0} could not be parsed (completely) - your test executable has probably crashed. Exception message: {1}.
        /// </summary>
        internal static string TestResultParse {
            get {
                return ResourceManager.GetString("TestResultParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test setup batch file.
        /// </summary>
        internal static string TestSetupBatchFile {
            get {
                return ResourceManager.GetString("TestSetupBatchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test teardown batch file.
        /// </summary>
        internal static string TestTeardownBatchFile {
            get {
                return ResourceManager.GetString("TestTeardownBatchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing tests on {0} threads.
        /// </summary>
        internal static string ThreadExecutionMessage {
            get {
                return ResourceManager.GetString("ThreadExecutionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown literal: {0}.
        /// </summary>
        internal static string UnknownLiteral {
            get {
                return ResourceManager.GetString("UnknownLiteral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown test case status: {0}.
        /// </summary>
        internal static string UnknownTestCase {
            get {
                return ResourceManager.GetString("UnknownTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using splitter based on test durations.
        /// </summary>
        internal static string UsingSplitterOnDuration {
            get {
                return ResourceManager.GetString("UsingSplitterOnDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using splitter based on number of tests.
        /// </summary>
        internal static string UsingSplitterOnNumber {
            get {
                return ResourceManager.GetString("UsingSplitterOnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} worst differences:.
        /// </summary>
        internal static string WorstDifferences {
            get {
                return ResourceManager.GetString("WorstDifferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XmlNode could not be parsed: &apos;{0}&apos;. Exception message: {1}.
        /// </summary>
        internal static string XmlNodeParse {
            get {
                return ResourceManager.GetString("XmlNodeParse", resourceCulture);
            }
        }
    }
}
