//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewProjectWizard.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewProjectWizard.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consume Google Test as:.
        /// </summary>
        public static string ConsumeAs {
            get {
                return ResourceManager.GetString("ConsumeAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic Library (.dll).
        /// </summary>
        public static string DynamicLib {
            get {
                return ResourceManager.GetString("DynamicLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link dynamically (Recommended).
        /// </summary>
        public static string LinkDynamic {
            get {
                return ResourceManager.GetString("LinkDynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link statically.
        /// </summary>
        public static string LinkStatic {
            get {
                return ResourceManager.GetString("LinkStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No project&gt;.
        /// </summary>
        public static string NoProject {
            get {
                return ResourceManager.GetString("NoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find NuGet.VisualStudio.Interop.dll. Wizard cannot continue..
        /// </summary>
        public static string NuGetInteropNotFound {
            get {
                return ResourceManager.GetString("NuGetInteropNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++ runtime libraries:.
        /// </summary>
        public static string RuntimeLibs {
            get {
                return ResourceManager.GetString("RuntimeLibs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select project to test (Optional):.
        /// </summary>
        public static string SelectProject {
            get {
                return ResourceManager.GetString("SelectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static Library (.lib).
        /// </summary>
        public static string StaticLib {
            get {
                return ResourceManager.GetString("StaticLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows SDK not found..
        /// </summary>
        public static string WinSDKNotFound {
            get {
                return ResourceManager.GetString("WinSDKNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Project Configuration.
        /// </summary>
        public static string WizardTitle {
            get {
                return ResourceManager.GetString("WizardTitle", resourceCulture);
            }
        }
    }
}
